services:
  - type: web
    name: waypoint-fleet-api
    runtime: node
    rootDir: server
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://waypoint-fleet.vercel.app
      - key: postgresql://waypoint:j7jDb5S0u5L1r0l4btqpZUDzA3JLlD4o@dpg-d94n5u5ckfvc73aahjhg-a/waypoint_fleet
        fromDatabase:
          name: waypoint-fleet-db
          property: connectionString

databases:
  - name: waypoint-fleet-db
    plan: free
    databaseName: waypoint_fleet
    user: waypoint
