/* ── Mock data ─────────────────────────────────────────────────────────────
   Replace these with API calls in the relevant page / context files.
   Each VEHICLES entry maps directly to one fleet record from the backend.
   ───────────────────────────────────────────────────────────────────────── */

export const VEHICLES = [
  {
    id: "ARV-24-791",
    image: "/cars/hyundai-sonata.svg",
    type: "Raya",
    model: "Hyundai Sonata",
    modelYear: 2024,
    assetNo: "ARV-24-791",
    month: "Jun-24",
    engineCC: "—",
    color: "White",
    colorHex: "#EDEFF4",
    fuelType: "Petrol",
    transmission: "Automatic",
    seating: "4 Seater",
    status: "Active",
    owner: "Umer Pervaiz Mughal",
    assignedTo: "Ahmad Salman",
    department: "Track & Snap",
    allocatedOn: "Jun-24",
    person: {
      name: "Ahmad Salman",
      title: "Group Chief Supply Chain Officer",
      department: "Supply Chain",
      office: "Raya HQ",
      employeeId: "ARF",
      email: "ahmad.salman@raya.com",
      contact: "+966 50 123 4567",
      initials: "AS",
      hue: 222,
    },
    notes:
      "This vehicle is allocated for official use only. Please ensure proper maintenance and compliance with company policy.",
  },
  {
    id: "ARV-24-552",
    image: "/cars/toyota-camry.svg",
    type: "Sedan",
    model: "Toyota Camry",
    modelYear: 2023,
    assetNo: "ARV-24-552",
    month: "Mar-24",
    engineCC: "2500",
    color: "Black",
    colorHex: "#23262E",
    fuelType: "Petrol",
    transmission: "Automatic",
    seating: "5 Seater",
    status: "Maintenance",
    owner: "Lubna Haider",
    assignedTo: "Imran Qureshi",
    department: "Finance",
    allocatedOn: "Mar-24",
    person: {
      name: "Imran Qureshi",
      title: "Finance Manager",
      department: "Finance",
      office: "Lahore Branch",
      employeeId: "FIN-118",
      email: "imran.qureshi@raya.com",
      contact: "+92 300 555 1122",
      initials: "IQ",
      hue: 268,
    },
    notes:
      "Vehicle currently in service for scheduled maintenance. Expected back on the road within 3 business days.",
  },
  {
    id: "ARV-24-330",
    image: "/cars/hyundai-tucson.svg",
    type: "SUV",
    model: "Hyundai Tucson",
    modelYear: 2024,
    assetNo: "ARV-24-330",
    month: "Apr-24",
    engineCC: "2000",
    color: "Silver",
    colorHex: "#C7CBD4",
    fuelType: "Petrol",
    transmission: "Automatic",
    seating: "5 Seater",
    status: "Active",
    owner: "Sara Khan",
    assignedTo: "Sara Khan",
    department: "Marketing",
    allocatedOn: "Apr-24",
    person: {
      name: "Sara Khan",
      title: "Marketing Director",
      department: "Marketing",
      office: "Lisbon Office",
      employeeId: "MKT-044",
      email: "sara.khan@raya.com",
      contact: "+351 91 234 5678",
      initials: "SK",
      hue: 18,
    },
    notes:
      "Assigned for regional client visits. Mileage log must be submitted at the end of each month.",
  },
  {
    id: "ARV-24-198",
    image: "/cars/byd-atto3.svg",
    type: "EV",
    model: "BYD Atto 3",
    modelYear: 2024,
    assetNo: "ARV-24-198",
    month: "Feb-24",
    engineCC: "—",
    color: "Blue",
    colorHex: "#3F6FE0",
    fuelType: "Electric",
    transmission: "Automatic",
    seating: "5 Seater",
    status: "Active",
    owner: "Bilal Ahmed",
    assignedTo: "Bilal Ahmed",
    department: "Operations",
    allocatedOn: "Feb-24",
    person: {
      name: "Bilal Ahmed",
      title: "Operations Lead",
      department: "Operations",
      office: "Raya HQ",
      employeeId: "OPS-027",
      email: "bilal.ahmed@raya.com",
      contact: "+966 55 876 2210",
      initials: "BA",
      hue: 162,
    },
    notes:
      "Electric fleet unit — charge to at least 80% before long-distance trips. Home charging reimbursed monthly.",
  },
  {
    id: "ARV-23-905",
    image: "/cars/toyota-hilux.png",
    type: "Pickup",
    model: "Toyota Hilux",
    modelYear: 2023,
    assetNo: "ARV-23-905",
    month: "Nov-23",
    engineCC: "2800",
    color: "Grey",
    colorHex: "#7C828F",
    fuelType: "Diesel",
    transmission: "Manual",
    seating: "5 Seater",
    status: "Inactive",
    owner: "Hamza Tariq",
    assignedTo: "Unassigned",
    department: "Logistics",
    allocatedOn: "Nov-23",
    person: {
      name: "Hamza Tariq",
      title: "Logistics Coordinator",
      department: "Logistics",
      office: "Lahore Branch",
      employeeId: "LOG-061",
      email: "hamza.tariq@raya.com",
      contact: "+92 301 778 9043",
      initials: "HT",
      hue: 32,
    },
    notes:
      "Currently parked pending reassignment. Awaiting department clearance before next allocation.",
  },
];

export const NAV_ITEMS = [
  { key: "dashboard",     label: "Dashboard",     icon: "LayoutDashboard" },
  { key: "vehicles",      label: "Vehicles",      icon: "Car"             },
  { key: "allocations",   label: "Allocations",   icon: "ClipboardList"   },
  { key: "people",        label: "People",        icon: "Users"           },
  { key: "reports",       label: "Reports",       icon: "BarChart3"       },
  { key: "notifications", label: "Notifications", icon: "Bell"            },
  { key: "settings",      label: "Settings",      icon: "Settings"        },
];
