// Same 5-vehicle mock fleet the frontend used to seed localStorage with
// (src/constants/data.js), ported here so a fresh database boots with the
// same demo data instead of starting empty.
export const SEED_VEHICLES = [
  {
    assetNo: "ARV-24-791",
    type: "Raya",
    model: "Hyundai Sonata",
    modelYear: 2024,
    month: "Jun-24",
    engineCC: "—",
    color: "White",
    colorHex: "#EDEFF4",
    fuelType: "Petrol",
    transmission: "Automatic",
    seating: "4 Seater",
    status: "Active",
    owner: "Umer Pervaiz Mughal",
    assignedTo: "Ahmad Salman",
    department: "Track & Snap",
    allocatedOn: "Jun-24",
    notes:
      "This vehicle is allocated for official use only. Please ensure proper maintenance and compliance with company policy.",
    person: {
      name: "Ahmad Salman",
      title: "Group Chief Supply Chain Officer",
      department: "Supply Chain",
      office: "Raya HQ",
      employeeId: "ARF",
      email: "ahmad.salman@raya.com",
      contact: "+966 50 123 4567",
      hue: 222,
    },
  },
  {
    assetNo: "ARV-24-552",
    type: "Sedan",
    model: "Toyota Camry",
    modelYear: 2023,
    month: "Mar-24",
    engineCC: "2500",
    color: "Black",
    colorHex: "#23262E",
    fuelType: "Petrol",
    transmission: "Automatic",
    seating: "5 Seater",
    status: "Maintenance",
    owner: "Lubna Haider",
    assignedTo: "Imran Qureshi",
    department: "Finance",
    allocatedOn: "Mar-24",
    notes:
      "Vehicle currently in service for scheduled maintenance. Expected back on the road within 3 business days.",
    person: {
      name: "Imran Qureshi",
      title: "Finance Manager",
      department: "Finance",
      office: "Lahore Branch",
      employeeId: "FIN-118",
      email: "imran.qureshi@raya.com",
      contact: "+92 300 555 1122",
      hue: 268,
    },
  },
  {
    assetNo: "ARV-24-330",
    type: "SUV",
    model: "Hyundai Tucson",
    modelYear: 2024,
    month: "Apr-24",
    engineCC: "2000",
    color: "Silver",
    colorHex: "#C7CBD4",
    fuelType: "Petrol",
    transmission: "Automatic",
    seating: "5 Seater",
    status: "Active",
    owner: "Sara Khan",
    assignedTo: "Sara Khan",
    department: "Marketing",
    allocatedOn: "Apr-24",
    notes: "Assigned for regional client visits. Mileage log must be submitted at the end of each month.",
    person: {
      name: "Sara Khan",
      title: "Marketing Director",
      department: "Marketing",
      office: "Lisbon Office",
      employeeId: "MKT-044",
      email: "sara.khan@raya.com",
      contact: "+351 91 234 5678",
      hue: 18,
    },
  },
  {
    assetNo: "ARV-24-198",
    type: "EV",
    model: "BYD Atto 3",
    modelYear: 2024,
    month: "Feb-24",
    engineCC: "—",
    color: "Blue",
    colorHex: "#3F6FE0",
    fuelType: "Electric",
    transmission: "Automatic",
    seating: "5 Seater",
    status: "Active",
    owner: "Bilal Ahmed",
    assignedTo: "Bilal Ahmed",
    department: "Operations",
    allocatedOn: "Feb-24",
    notes: "Electric fleet unit — charge to at least 80% before long-distance trips. Home charging reimbursed monthly.",
    person: {
      name: "Bilal Ahmed",
      title: "Operations Lead",
      department: "Operations",
      office: "Raya HQ",
      employeeId: "OPS-027",
      email: "bilal.ahmed@raya.com",
      contact: "+966 55 876 2210",
      hue: 162,
    },
  },
  {
    assetNo: "ARV-23-905",
    type: "Pickup",
    model: "Toyota Hilux",
    modelYear: 2023,
    month: "Nov-23",
    engineCC: "2800",
    color: "Grey",
    colorHex: "#7C828F",
    fuelType: "Diesel",
    transmission: "Manual",
    seating: "5 Seater",
    status: "Inactive",
    owner: "Hamza Tariq",
    assignedTo: "Unassigned",
    department: "Logistics",
    allocatedOn: "Nov-23",
    notes: "Currently parked pending reassignment. Awaiting department clearance before next allocation.",
    person: {
      name: "Hamza Tariq",
      title: "Logistics Coordinator",
      department: "Logistics",
      office: "Lahore Branch",
      employeeId: "LOG-061",
      email: "hamza.tariq@raya.com",
      contact: "+92 301 778 9043",
      hue: 32,
    },
  },
];
